### ISSUE TITLE
Potential problem with mapnode related function

### ISSUE THREAD

**Issue by Exas4000** [KittenAqua/TrainworksModdingTools#131] opened 2020-12-11 00:47 UTC
https://pastebin.com/zwpT5WkS

Recent issue, Custom clan can load, is listed in the logbook. 
But unable to launch the clan since the new controller update. Previously was possible to launch a game prior it.

With my limited knowledge, i presume that a map node wasn't registered properly.

**Comment by RawsomeGH** [comment] 2020-12-11 14:13
Don't quite know what _exactly_ it's doing, but the problem is here:
https://github.com/KittenAqua/TrainworksModdingTools/blob/480e938e226ba072b2829bfe2354ece1a7b93a49/TrainworksModdingTools/Builders/MapNodeBuilders/RewardNodeDataBuilder.cs#L141-L158
`images` now has length 6, while `spritePaths` only has Count 5, so there's an index OoB.
Maybe someone who knows how to inspect the prefab (or which one is being referred to here) can look into this. :)

**Comment by RawsomeGH** [comment] 2020-12-11 16:39
Apparently the selection outline image ended up in there for keyboard / controller support.
It's the first sprite in the list, so just adding another entry to `spritePaths` should do it.

**Comment by TricksterGuy** [comment] 2023-06-16 03:48
I'm going to close this since there was PR that mentioned that it fixes this issue and I don't see this happening anymore.

**Comment by brandonandzeus** [comment] 2023-06-16 04:07
I'm going to close this since there was PR that mentioned that it fixes this issue and I don't see this happening anymore.

**Closed by brandonandzeus** 2023-06-16 04:07 UTC
